CREATE DATABASE IF NOT EXISTS chatapp_db;
USE chatapp_db;

CREATE TABLE IF NOT EXISTS User (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    contact_number VARCHAR(20) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS Chat (
    chatId INT AUTO_INCREMENT PRIMARY KEY,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ChatParticipants (
    chatId INT NOT NULL,
    userId INT NOT NULL,
    PRIMARY KEY (chatId, userId),
    FOREIGN KEY (chatId) REFERENCES Chat(chatId) ON DELETE CASCADE,
    FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Message (
    messageId INT AUTO_INCREMENT PRIMARY KEY,
    chatId INT NOT NULL,
    senderId INT NOT NULL,
    text TEXT NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(50) DEFAULT 'SENT',
    FOREIGN KEY (chatId) REFERENCES Chat(chatId) ON DELETE CASCADE,
    FOREIGN KEY (senderId) REFERENCES User(id) ON DELETE CASCADE
);
